/**
 * Rebuilds Eddy's Nado knowledge base from the official docs.
 *
 * Nado publishes llms-full.txt, the whole documentation set as one plain-text
 * file. Roughly the first 3,900 lines are conceptual docs — how margin works,
 * liquidations, fees, funding, order types, FAQs — and everything after is SDK
 * reference: long code samples in three languages. A trading assistant needs
 * the first part and would spend most of its context window on the second, so
 * this keeps the conceptual half and stops at the SDK boundary.
 *
 * The result is written as a JS module rather than a .md file so the serverless
 * bundler includes it; reading a stray .md at runtime depends on file-tracing
 * that quietly breaks on deploy.
 *
 * Usage: node scripts/fetch-docs.mjs
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const DOCS_URL = 'https://docs.nado.xyz/llms-full.txt';
const SDK_BOUNDARY = /^# Get Started$/m;

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'api', '_nado-knowledge.js');

const res = await fetch(DOCS_URL, {
  headers: { 'user-agent': 'eddy-nado-docs-sync' },
});
if (!res.ok) {
  throw new Error(`Fetching ${DOCS_URL} failed: ${res.status} ${res.statusText}`);
}

const full = await res.text();
const boundary = full.search(SDK_BOUNDARY);
const conceptual = boundary === -1 ? full : full.slice(0, boundary);

if (boundary === -1) {
  console.warn(
    'Could not find the "# Get Started" heading that marks the SDK reference. ' +
      'Keeping the full document — check whether the docs were restructured.',
  );
}

// Escaped for a template literal: backslashes first (so later escapes survive),
// then backticks and ${ so the docs cannot break out of the string.
const escaped = conceptual
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${');

writeFileSync(
  outPath,
  `// Generated by scripts/fetch-docs.mjs — do not edit by hand.\n` +
    `// Source: ${DOCS_URL}\n` +
    `// Retrieved: ${new Date().toISOString()}\n\n` +
    `export const NADO_DOCS = \`${escaped}\`;\n\n` +
    `export const NADO_DOCS_RETRIEVED_AT = ${JSON.stringify(new Date().toISOString())};\n`,
  'utf8',
);

const kb = Math.round(conceptual.length / 1024);
const approxTokens = Math.round(conceptual.length / 4 / 1000);
console.log(`Wrote ${outPath}`);
console.log(`Kept ${kb}KB of conceptual docs (~${approxTokens}K tokens)`);
